name: Execute jupyter notebooks

env:
  # URL for the external repository linked with the notebooks in this project.
  # This repository needs to be hosted un Github
  LINKED_REPO: aperezhortal/nb_gallery_template

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  get_target_branch:
    # https://pwgen88.medium.com/getting-branch-name-in-github-actions-based-on-workflow-trigger-1d10b8515d37
    name: Get target branch for the rendered notebooks
    runs-on: "ubuntu-latest"
    outputs:
      target_branch: ${{ steps.target_branch.outputs.branch }}
    steps:
      - name: Get target branch
        id: target_branch
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
            branch=$(echo ${GITHUB_REF##*/})
          elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            branch=$(echo $GITHUB_BASE_REF)
          else
            branch=unknown
          fi

          if [[ $branch == "dev" ]]; then
            echo "::set-output name=branch::test"
          else
            echo "::set-output name=branch::latest"
          fi

  run_notebooks:
    name: Execute jupyter notebooks
    runs-on: "ubuntu-latest"
    needs: get_branch

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Install mamba and create environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          environment-name: doc_builder
          extra-specs: python=3.8

      - name: Clone linked repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.LINKED_REPO }}
          path: ${{ env.LINKED_REPO }}

      - name: Install dependency from linked repository
        run: |
          echo "Here we should install the package"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute notebooks
        working-directory: ./docs/notebooks
        run: |
          jupyter nbconvert --to notebook --inplace --execute ./*.ipynb

      - name: Commit notebooks
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout --orphan ${RENDER_BRANCH}
          git commit -a -m "Rendering $GITHUB_SHA"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{needs.get_branch.outputs.target_branch }}
